#!/usr/bin/env python3
"""Rebuild checksum lock file for vector fixtures."""

from __future__ import annotations

import hashlib
from pathlib import Path

VECTORS_DIR = Path("pbt-rs/tests/vectors")
LOCK_FILE = VECTORS_DIR / "SHA256SUMS"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    if not VECTORS_DIR.exists():
        print(f"vector-checksums: missing directory: {VECTORS_DIR}")
        return 1

    lines: list[str] = []
    lines.append("# Auto-generated by scripts/update_vector_checksums.py")
    for file_path in sorted(VECTORS_DIR.glob("*.json")):
        digest = _sha256(file_path)
        lines.append(f"{digest}  {file_path.as_posix()}")

    LOCK_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"vector-checksums: wrote {LOCK_FILE}")
    print(f"vector-checksums: files={len(lines) - 1}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
