#!/usr/bin/env python3
"""Verify release bundle artifacts generated by pbt-rs/scripts/release_bundle.sh."""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from pathlib import Path

DIST = Path("dist")
REQUIRED = {
    "tarball": DIST / "pbt-rs-source.tar.gz",
    "sha_file": DIST / "pbt-rs-sha256.txt",
    "summary": DIST / "network-readiness-summary.txt",
    "manifest": DIST / "release-manifest.json",
    "signing_status": DIST / "signing-status.txt",
    "sbom": DIST / "sbom.spdx.json",
    "provenance": DIST / "provenance.intoto.jsonl",
}
SIGNING_WAIVER = DIST / "signing-waiver.json"


def is_release_mode() -> bool:
    env = os.environ.get("PBT_RELEASE_MODE", "").strip().lower()
    if env in {"1", "true", "yes", "on"}:
        return True
    if env in {"0", "false", "no", "off"}:
        return False

    for key in ("GITHUB_REF_NAME", "BRANCH_NAME"):
        ref = os.environ.get(key, "").strip()
        if ref in {"main", "master"}:
            return True
    return False


def fail(message: str) -> int:
    print(f"release-artifacts: FAIL: {message}")
    return 1


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_sha_file(path: Path) -> tuple[str, str]:
    line = path.read_text(encoding="utf-8").strip()
    match = re.match(r"^([a-fA-F0-9]{64})\s+(.+)$", line)
    if not match:
        raise ValueError("invalid sha256 file format")
    return match.group(1).lower(), match.group(2)


def main() -> int:
    for name, path in REQUIRED.items():
        if not path.exists():
            return fail(f"missing required artifact: {name} at {path}")

    try:
        manifest = json.loads(REQUIRED["manifest"].read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover
        return fail(f"invalid manifest JSON: {exc}")

    try:
        tarball_sha_file, tarball_path_in_sha = parse_sha_file(REQUIRED["sha_file"])
    except ValueError as exc:
        return fail(f"invalid checksum file: {exc}")
    tarball_actual = sha256(REQUIRED["tarball"])
    if tarball_sha_file != tarball_actual:
        return fail("tarball checksum mismatch between tarball and pbt-rs-sha256.txt")

    tarball_path_value = tarball_path_in_sha.strip()
    expected_tarball = REQUIRED["tarball"]
    candidate_tarball = Path(tarball_path_value)
    if candidate_tarball.is_absolute():
        if candidate_tarball.resolve() != expected_tarball.resolve():
            return fail("pbt-rs-sha256.txt references unexpected tarball path")
    else:
        if candidate_tarball.name != expected_tarball.name:
            return fail("pbt-rs-sha256.txt references unexpected tarball path")

    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, list):
        return fail("manifest artifacts must be a list")

    by_path = {entry.get("path"): entry for entry in artifacts if isinstance(entry, dict)}
    for required_path in [
        "dist/pbt-rs-source.tar.gz",
        "dist/pbt-rs-sha256.txt",
        "dist/network-readiness-summary.txt",
    ]:
        if required_path not in by_path:
            return fail(f"manifest missing artifact entry for {required_path}")

    if by_path["dist/pbt-rs-source.tar.gz"].get("sha256") != tarball_actual:
        return fail("manifest tarball checksum does not match actual tarball")

    if by_path["dist/pbt-rs-sha256.txt"].get("sha256") != sha256(REQUIRED["sha_file"]):
        return fail("manifest sha-file checksum does not match actual file")

    if by_path["dist/network-readiness-summary.txt"].get("sha256") != sha256(REQUIRED["summary"]):
        return fail("manifest summary checksum does not match actual file")

    release_mode = is_release_mode()
    signing_status_text = REQUIRED["signing_status"].read_text(encoding="utf-8")
    if "signing: enabled" in signing_status_text:
        for sig_name in ["release-manifest.json.sig", "pbt-rs-source.tar.gz.sig"]:
            sig_path = DIST / sig_name
            if not sig_path.exists():
                return fail(f"signing enabled but missing signature artifact: {sig_name}")
    else:
        if release_mode:
            return fail("release mode requires signatures; waiver is not allowed")
        if not SIGNING_WAIVER.exists():
            return fail("strict signing policy requires signatures or dist/signing-waiver.json")
        try:
            waiver = json.loads(SIGNING_WAIVER.read_text(encoding="utf-8"))
        except Exception as exc:
            return fail(f"invalid signing waiver json: {exc}")
        required_fields = ["reason", "approved_by", "approved_at_utc", "expires_at_utc"]
        missing = [field for field in required_fields if not waiver.get(field)]
        if missing:
            return fail("signing waiver missing fields: " + ", ".join(missing))

    try:
        sbom = json.loads(REQUIRED["sbom"].read_text(encoding="utf-8"))
    except Exception as exc:
        return fail(f"invalid sbom json: {exc}")
    if not isinstance(sbom, dict) or "SPDXID" not in sbom:
        return fail("sbom must contain SPDXID")

    provenance_lines = REQUIRED["provenance"].read_text(encoding="utf-8").splitlines()
    if not provenance_lines:
        return fail("provenance file must not be empty")
    try:
        statement = json.loads(provenance_lines[0])
    except Exception as exc:
        return fail(f"invalid provenance statement JSON: {exc}")

    subjects = statement.get("subject") if isinstance(statement, dict) else None
    if not isinstance(subjects, list) or not subjects:
        return fail("provenance subject list must be non-empty")
    digest = subjects[0].get("digest", {}).get("sha256") if isinstance(subjects[0], dict) else None
    if not isinstance(digest, str) or not re.fullmatch(r"[a-f0-9]{64}", digest):
        return fail("provenance digest.sha256 must be 64-char lowercase hex")
    if digest != tarball_actual:
        return fail("provenance digest must match dist/pbt-rs-source.tar.gz checksum")

    print("release-artifacts: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
