#!/usr/bin/env python3
"""Verify release bundle artifacts generated by pbt-rs/scripts/release_bundle.sh."""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path


DIST = Path("dist")
REQUIRED = {
    "tarball": DIST / "pbt-rs-source.tar.gz",
    "sha_file": DIST / "pbt-rs-sha256.txt",
    "summary": DIST / "network-readiness-summary.txt",
    "manifest": DIST / "release-manifest.json",
    "signing_status": DIST / "signing-status.txt",
}


def fail(message: str) -> int:
    print(f"release-artifacts: FAIL: {message}")
    return 1


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def parse_sha_file(path: Path) -> tuple[str, str]:
    line = path.read_text(encoding="utf-8").strip()
    match = re.match(r"^([a-fA-F0-9]{64})\s+(.+)$", line)
    if not match:
        raise ValueError("invalid sha256 file format")
    return match.group(1).lower(), match.group(2)


def main() -> int:
    for name, path in REQUIRED.items():
        if not path.exists():
            return fail(f"missing required artifact: {name} at {path}")

    try:
        manifest = json.loads(REQUIRED["manifest"].read_text(encoding="utf-8"))
    except Exception as exc:  # pragma: no cover
        return fail(f"invalid manifest JSON: {exc}")

    tarball_sha_file, tarball_path_in_sha = parse_sha_file(REQUIRED["sha_file"])
    tarball_actual = sha256(REQUIRED["tarball"])
    if tarball_sha_file != tarball_actual:
        return fail("tarball checksum mismatch between tarball and pbt-rs-sha256.txt")

    tarball_path_value = tarball_path_in_sha.strip()
    expected_tarball = REQUIRED["tarball"]
    candidate_tarball = Path(tarball_path_value)
    if candidate_tarball.is_absolute():
        if candidate_tarball.resolve() != expected_tarball.resolve():
            return fail("pbt-rs-sha256.txt references unexpected tarball path")
    else:
        if candidate_tarball.name != expected_tarball.name:
            return fail("pbt-rs-sha256.txt references unexpected tarball path")

    artifacts = manifest.get("artifacts")
    if not isinstance(artifacts, list):
        return fail("manifest artifacts must be a list")

    by_path = {entry.get("path"): entry for entry in artifacts if isinstance(entry, dict)}
    for required_path in [
        "dist/pbt-rs-source.tar.gz",
        "dist/pbt-rs-sha256.txt",
        "dist/network-readiness-summary.txt",
    ]:
        if required_path not in by_path:
            return fail(f"manifest missing artifact entry for {required_path}")

    if by_path["dist/pbt-rs-source.tar.gz"].get("sha256") != tarball_actual:
        return fail("manifest tarball checksum does not match actual tarball")

    if by_path["dist/pbt-rs-sha256.txt"].get("sha256") != sha256(REQUIRED["sha_file"]):
        return fail("manifest sha-file checksum does not match actual file")

    if by_path["dist/network-readiness-summary.txt"].get("sha256") != sha256(REQUIRED["summary"]):
        return fail("manifest summary checksum does not match actual file")

    signing_status_text = REQUIRED["signing_status"].read_text(encoding="utf-8")
    if "signing: enabled" in signing_status_text:
        for sig_name in ["release-manifest.json.sig", "pbt-rs-source.tar.gz.sig"]:
            sig_path = DIST / sig_name
            if not sig_path.exists():
                return fail(f"signing enabled but missing signature artifact: {sig_name}")
    elif "signing: unavailable" in signing_status_text or "signing: failed" in signing_status_text:
        # Placeholder mode is acceptable; signatures may be absent.
        pass
    else:
        return fail("signing-status.txt missing recognized signing state")

    print("release-artifacts: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
